export const options = [
  { id: "react", name: "React", icon: "/images/react.svg" },
  { id: "nextjs", name: "Next.js", icon: "/images/nextjs.svg" },
  {
    id: "tanstack-query",
    name: "Tanstack Query",
    icon: "/images/react-query.svg",
  },
  { id: "docker", name: "Docker", icon: "/images/docker.svg" },
  { id: "astro", name: "Astro", icon: "/images/astro.svg" },
  { id: "supabase", name: "Supabase", icon: "/images/supabase.svg" },
  { id: "hono", name: "Hono", icon: "/images/hono.svg" },
  { id: "firebase", name: "Firebase", icon: "/images/firebase.svg" },
  { id: "pinia", name: "Pinia", icon: "/images/pinia.svg" },
  { id: "vite", name: "Vite", icon: "/images/vitejs.svg" },
  {
    id: "testing-library",
    name: "Testing Library",
    icon: "/images/testing-library.svg",
  },
  { id: "vitest", name: "Vitest", icon: "/images/vitest.svg" },
  { id: "bunny", name: "Bunny", icon: "/images/bunny-net.svg" },
  { id: "mongodb", name: "MongoDB", icon: "/images/mongodb.svg" },
  { id: "bun", name: "Bun", icon: "/images/bun.svg" },
  { id: "nuxt", name: "Nuxt", icon: "/images/nuxt.svg" },
  { id: "remix", name: "Remix", icon: "/images/remix.svg" },
  { id: "kubernetes", name: "Kubernetes", icon: "/images/kubernetes.svg" },
  { id: "tailwind", name: "Tailwind CSS", icon: "/images/tailwind.svg" },
  { id: "redis", name: "Redis", icon: "/images/redis.svg" },
  { id: "redux", name: "Redux", icon: "/images/redux.svg" },
  { id: "rust", name: "Rust", icon: "/images/rust.svg" },
  { id: "postman", name: "Postman", icon: "/images/postman.svg" },
  { id: "figma", name: "Figma", icon: "/images/figma.svg" },
  { id: "babel", name: "Babel", icon: "/images/babel.svg" },
  { id: "webpack", name: "Webpack", icon: "/images/webpack.svg" },
];
